### ISSUE TITLE
Can't add new feeds and old feeds don't refresh

### ISSUE THREAD

**Issue by tux4us** [florisluiten/rssreader#13]
UT 16.04 xenial
Try to add e new feed ends with "The specified location seems not a valid rss feed".
Try with some feeds brings the same result.
Old feeds in rssreader don't refresh since last OTA.

**Comment by florisluiten** [comment]
Hello tux4us,

First of all, I apologize for my late response, for I had disabled e-mail notifications for the issue tracker and did not see your issue. 

I have not actively been working on this projects for quite some time, because I no longer own my Ubuntu Phone (and also no longer own the PC with the development setup). I'm glad however that there are still other people enjoying this app (although, you probably aren't enjoying it too much if the feeds are not refreshing).

I have to setup my development machine from scratch before I can start working on your issue. The past hast taught me that this can be quite challenging; also I'm not quite sure whether my approach of using a HTML+JavaScript to build an app is still supported. So I'm not you that I can fix it, soon, if i can fix it at all. However, I appreciate your time and effort of opening an issue and am willing to investigate further.

If I may ask, how did you install the app? Do you know what version you are using?

**Comment by florisluiten** [comment]
Hello,

Me again.

I've published version 0.3.0 to the OpenStore. Can you please update to this version? That should resolve your problem.

If you still have issues, feel free to create a new issue (and reference to this one, please).

Thanks again,

Floris
