### ISSUE TITLE
Paste Feed Url

### ISSUE THREAD

**Issue by balcy** [florisluiten/rssreader#5]
When adding new feeds, I'd like to paste the feed url.

**Comment by florisluiten** [comment]
Hi again @altpapier! Thanks again for your feedback, let's make this a regular thing, okay?

I agree that unable to paste and URL really sucks. Most are hard enough to remember, let alone type on a touch device. 

The only thing is: It did work a while back, but somewhere along the updates of Ubuntu Touch it stopped working. 

I'm not sure how much I can do about it, since it's a HTML Toolkit app. I have little control over these kind of things. That said, there might be a another way to request for user input with support for pasting, so I'll look into workarounds. 
I think it's possible (afaik the Twitter app is also a HTML Toolkit app _with_ support for pasting), but it might take me some time to figure it out.

So, let me take some time to figure this out. I'll keep you updated.

**Comment by florisluiten** [comment]
Hi Chris,

Last night (2016-04-06 23:00 GMT) I've received a System update (version 11) for my phone. After installing this System update it seems it is possible to copy+paste in the "Add feed" box. So it has been solved!

**Comment by balcy** [comment]
Hi Floris! Thank you for the info, I can confirm that it is working on BQ Aquaris 4.5. Just one thing: Is the cancel button in the insert feed page working ? It seems to have no effect on my phone?

**Comment by balcy** [comment]
... actually I meant it behaves like the Add button

**Comment by florisluiten** [comment]
Hi Chris,

Yes, you are right. It did not really cancel the action. This was actually the same issue with the two feeds being deleted as described in issue #4. So, my fixes from that issue should also help with this. Look at version 0.1.8 to see this fixed.

Thanks again for your feedback. You are a great help.

Kind regards,

Floris
