### ISSUE TITLE
Stopped working after OTA-12

### ISSUE THREAD

**Issue by anupam207** [florisluiten/rssreader#6]
App can't get past the splash-screen, crashes immediately.
Device: bq E5

**Comment by florisluiten** [comment]
Thank you for your time to create this bugreport.

I can confirm that the app crashes after the latest OTA update of Ubuntu 
Touch (Version 14 in the case of the Meizu MX4). That might sound as bad 
news, but at least allows me to reproduce the bug and hopefully be able to 
trace the origin of the crash and introducing a fix.
The bad news ofcourse, that the app does not work on latest Ubuntu Touch on 
multiple devices. I will update the app description to notify people about 
this.

Since this is a mayor bug I'll try my best to look into this ASAP. Please 
be patient while I investigate, hopefully I will be able to push the fix 
within 24h, hopefully sooner. This, ofcourse,  depends on the cause of the 
bug.

Thank you again for your report!

On Wednesday, 27 July 2016 20:47:42 CEST, anupam207 
notifications@github.com wrote:

> App can't get past the splash-screen, crashes immediately.
> Device: bq E5
> 
> -*

## 

Sent from my Ubuntu device

**Comment by florisluiten** [comment]
Hi again @anupam207!

It took me some time to figure it out. The underlying application to run the app has been removed in the latest OTA.
I've managed fix this and all data should have been saved. Please upgrade to the latest version 0.2.2 to test if this also fixes the issue for you on your BQ.

Thank you again for making this app better. If you have any more feedback I'm happy to hear from you :-)

**Comment by anupam207** [comment]
@florisluiten It works again! Tank you a lot.

**Comment by florisluiten** [comment]
That is good news, great to hear it works.

Thank you for your feedback. Have nice day.

On Thursday, 28 July 2016 22:07:12 CEST, anupam207 
notifications@github.com wrote:

> @florisluiten It works again! Tank you a lot.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/florisluiten/rssreader/issues/6#issuecomment-236009658

## 

Sent from my Ubuntu device
