### ISSUE TITLE
Open Store

### ISSUE THREAD

**Issue by balcy** [florisluiten/rssreader#8]
Hi Floris,

what about submitting the app to the Open Store (https://open.uappexplorer.com) ?
Then it can still be downloaded after Canonical will close its App store by the end of the year.

kind regards,
Chris

**Comment by florisluiten** [comment]
Hi Chris,

Thank you for your suggestion, see https://open.uappexplorer.com/app/rssreader.florisluiten

This for now is just the 'original' unmodified version that is available in the Ubuntu Store, but since the latter will not be available soon the Open Store version is probably more future-proof :-)

Thanks again for your help!

Kind regards,

Floris
